//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleCheckboxInsert.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAnswer> tblAnswers { get; set; }
        public virtual DbSet<tblQuestion> tblQuestions { get; set; }
        public virtual DbSet<tblResult> tblResults { get; set; }
    
        public virtual ObjectResult<AllQuestionAndAnswer_Result> AllQuestionAndAnswer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AllQuestionAndAnswer_Result>("AllQuestionAndAnswer");
        }
    
        public virtual int DeleteQuestionAndAnswer(Nullable<int> tblQuestionID)
        {
            var tblQuestionIDParameter = tblQuestionID.HasValue ?
                new ObjectParameter("tblQuestionID", tblQuestionID) :
                new ObjectParameter("tblQuestionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteQuestionAndAnswer", tblQuestionIDParameter);
        }
    
        public virtual ObjectResult<GetAllQuestionAnswer_Result> GetAllQuestionAnswer()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllQuestionAnswer_Result>("GetAllQuestionAnswer");
        }
    
        public virtual ObjectResult<JoinQuestionAnswerResultCheckbox_Result> JoinQuestionAnswerResultCheckbox()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinQuestionAnswerResultCheckbox_Result>("JoinQuestionAnswerResultCheckbox");
        }
    }
}
